# Buổi 03: Phân tích dữ liệu với Python

In [12]:
# !rm -r pydata-book
# !git clone https://github.com/wesm/pydata-book.git
!ls pydata-book/
# !sudo rm -r pydata-book/.git

COPYING     ch02.ipynb	ch06.ipynb  ch10.ipynb	datasets
README.md   ch03.ipynb	ch07.ipynb  ch11.ipynb	examples
appa.ipynb  ch04.ipynb	ch08.ipynb  ch12.ipynb	requirements.txt
appb.ipynb  ch05.ipynb	ch09.ipynb  ch13.ipynb


In [28]:
# !git status
# !git add . -n
# !git add .
# !git commit -m "buoi03"
# !git push
# !git status
# !git push --force # ép phải commit (nếu xảy ra xung đột)
# !git reset HEAD~  # phục hồi lại trạng thái commit gần nhất

# !git add .
# !git commit -m "buoi03"
# !git push

In [32]:
# !ls
# !mv pydata-book/ ../
# !git add . -n
# !git add .
# !git commit -m "buoi03"
# !git push

In [36]:
v = list(range(1, 6))
print(v)
print(2 * v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [38]:
import numpy as np
v = np.arange(1, 6)
print(v)
print(2 * v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [40]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [42]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [46]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [2]:
import numpy as np

# Tạo mảng toàn số 0
a = np.zeros((5, 5))
print("Mảng toàn số 0:\n", a)

# Tạo mảng toàn số 1
b = np.ones((1, 2))
print("Mảng toàn số 1:\n", b)

# Tạo mảng với giá trị cố định là 7
c = np.full((2, 2), 7)
print("Mảng toàn số 7:\n", c)

# Tạo ma trận đơn vị 2x2
d = np.eye(2)
print("Ma trận đơn vị:\n", d)

# Tạo mảng với giá trị ngẫu nhiên từ 0 đến 1
e = np.random.random((2, 2))
print("Mảng ngẫu nhiên:\n", e)


Mảng toàn số 0:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Mảng toàn số 1:
 [[1. 1.]]
Mảng toàn số 7:
 [[7 7]
 [7 7]]
Ma trận đơn vị:
 [[1. 0.]
 [0. 1.]]
Mảng ngẫu nhiên:
 [[0.58733915 0.73928744]
 [0.74592243 0.26530296]]


In [11]:
import numpy as np
a = np.arange(15)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

a = a.reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
1
int64
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64


In [14]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [17]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
b = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64


In [26]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)


## Pandas

In [7]:
import pandas as pd
from IPython.display import display

df = pd.DataFrame({
        "a": [4, 5, 6],
        "b": [7, 8, 9],
        "c": [10, 11, 12]
    },
        index = [1, 2, 3])

display(df)
display(df['a'])
display(df.loc[2])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

1    4
2    5
3    6
Name: a, dtype: int64

a     5
b     8
c    11
Name: 2, dtype: int64

In [9]:
type(df)

pandas.core.frame.DataFrame

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported


In [13]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [22]:
dates = pd.date_range('20181001', periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [23]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [35]:
df_a = pd.DataFrame(
    {'A': pd.Series([1,3,5,np.nan,6,8])}, 
    dtype=float)
df_a

A
0  1.0
1  3.0
2  5.0
3  NaN
4  6.0
5  8.0

In [36]:
df = pd.DataFrame(
    np.random.randn(6,4), 
    index=dates, 
    columns=list('ABCD'))
df

A         B         C         D
2018-10-01  1.110886  1.027036  0.791661 -1.262097
2018-10-02 -0.069411  0.834350  0.017643 -2.956131
2018-10-03  0.426844 -0.878510  0.699349  0.311923
2018-10-04  0.400394  0.168022  1.456345 -0.636078
2018-10-05 -0.732078 -0.890757  2.800093  0.981054
2018-10-06 -0.063057 -0.440794  0.178016 -1.045722

In [38]:
df = pd.DataFrame(
    np.random.randn(3,5), 
    index=['student1','student2','student3'], 
    columns=list('ABCDE'))
df


A         B         C         D         E
student1 -1.664760  0.102781  1.033670  0.942948 -0.446705
student2  1.452311  0.300633  1.370753  0.143413  0.704338
student3  0.576471  0.295171 -0.245722 -0.116716  0.492651

In [40]:
df2 = pd.DataFrame(
    { 
        'A' : 1.,
        'B' : pd.Timestamp('20181001'),
        'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
        'D' : np.array([3] * 4,dtype='int32'),
        'E' : pd.Categorical(["test","train","test","train"]),
        'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [45]:
df3 = pd.DataFrame(
    [
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'}
    ]
)
df3

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

## Kết thúc